### ISSUE TITLE
StimulusSet in brainio does not have get_image

### ISSUE THREAD

**Issue by briancheung** [brain-score/model-tools#65]
>   File "/home/allagash/miniconda3/envs/fuzzy-spoon/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'StimulusSet' object has no attribute 'get_image'

https://github.com/brain-score/model-tools/blob/dfee128b4b5efea0cf0c29fd873de288d7c98153/model_tools/activations/core.py#L54

This line appears to be referencing a function that no longer exists in `StimulusSet`
https://github.com/brain-score/brainio/blob/main/brainio/stimuli.py#L10

**Comment by mschrimpf** [comment]
Which line are you referring to? `get_image` was renamed to `get_stimulus`, are we still using `get_image` somewhere?

**Comment by briancheung** [comment]
Looking more closely, it seems my specific installation still used get_image(). There may have been a window of time when `brainio` was not synced with `model-tools`. Either way, I was able to resolve this by updating model-tools. Thanks!
